stages:          # List of stages for jobs, and their order of execution
  - build

build-release:   # Tagged builds
  image: docker.slock.it/build-images/cmake:rust
  rules:
    - if: ($CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG)      
  stage: build
  script:
    - ./build.sh
    - test -f libvade_evan.a # just to check if artifact exists
  artifacts:
    paths:
      - libvade_evan.a
    expire_in: 1 day

build-nightly:   # Nightly builds
  image: docker.slock.it/build-images/cmake:rust
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"       
  stage: build
  script:
    - ./build.sh
    - test -f libvade_evan.a # just to check if artifact exists
  artifacts:
    paths:
      - libvade_evan.a
    expire_in: 1 day

# manual builds for fast testing
# NOTE: It is manual and the artifacts expire in 15 minutes because these builds are not
# expected to be stable. They are more for tweeking and playing around. After which a 
# scheduled nightly will be automatically created. 
build:   
  image: docker.slock.it/build-images/cmake:rust
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"      
  stage: build
  when: manual
  allow_failure: false
  script:
    - ./build.sh
    - test -f libvade_evan.a # just to check if artifact exists
  artifacts:
    paths:
      - libvade_evan.a
    expire_in: 15 minutes
