[target.x86_64-unknown-linux-gnu]
dockerfile = "../dockerfiles/Dockerfile.x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
dockerfile = "../dockerfiles/Dockerfile.aarch64-unknown-linux-gnu"

[target.arm-unknown-linux-gnueabihf]
dockerfile = "../dockerfiles/Dockerfile.arm-unknown-linux-gnueabihf"

[target.x86_64-pc-windows-gnu]
dockerfile = "../dockerfiles/Dockerfile.x86_64-pc-windows-gnu"